import type { AuditAction } from "@ardenfold/contracts";

export const auditActionMessageKeys: Readonly<Record<AuditAction, string>> = {
    "organization.created": "audit.actions.organizationCreated",
    "organization.updated": "audit.actions.organizationUpdated",
    "site.created": "audit.actions.siteCreated",
    "invitation.created": "audit.actions.invitationCreated",
    "invitation.cancelled": "audit.actions.invitationCancelled",
    "invitation.accepted": "audit.actions.invitationAccepted",
    "membership.role_changed": "audit.actions.membershipRoleChanged",
    "membership.suspended": "audit.actions.membershipSuspended",
    "membership.removed": "audit.actions.membershipRemoved",
    "party.created": "audit.actions.partyCreated",
    "party.updated": "audit.actions.partyUpdated",
    "party.roles_changed": "audit.actions.partyRolesChanged",
    "party.details_changed": "audit.actions.partyDetailsChanged",
    "party.archived": "audit.actions.partyArchived",
    "party.restored": "audit.actions.partyRestored",
    "asset.created": "audit.actions.assetCreated",
    "asset.updated": "audit.actions.assetUpdated",
    "asset.lifecycle_changed": "audit.actions.assetLifecycleChanged",
    "asset.identifier_added": "audit.actions.assetIdentifierAdded",
    "asset.identifier_changed": "audit.actions.assetIdentifierChanged",
    "asset.identifier_retired": "audit.actions.assetIdentifierRetired",
    "asset.archived": "audit.actions.assetArchived",
    "asset.restored": "audit.actions.assetRestored",
    "asset.relationship_started": "audit.actions.assetRelationshipStarted",
    "asset.relationship_ended": "audit.actions.assetRelationshipEnded",
    "asset.relationship_corrected": "audit.actions.assetRelationshipCorrected",
};
