import type { AuditAction } from "@ardenfold/contracts";

export const auditActionMessageKeys: Readonly<Record<AuditAction, string>> = {
    "organization.created": "audit.actions.organizationCreated",
    "organization.updated": "audit.actions.organizationUpdated",
    "site.created": "audit.actions.siteCreated",
    "invitation.created": "audit.actions.invitationCreated",
    "invitation.cancelled": "audit.actions.invitationCancelled",
    "invitation.accepted": "audit.actions.invitationAccepted",
    "membership.role_changed": "audit.actions.membershipRoleChanged",
    "membership.suspended": "audit.actions.membershipSuspended",
    "membership.removed": "audit.actions.membershipRemoved",
    "party.created": "audit.actions.partyCreated",
    "party.updated": "audit.actions.partyUpdated",
    "party.roles_changed": "audit.actions.partyRolesChanged",
    "party.details_changed": "audit.actions.partyDetailsChanged",
    "party.archived": "audit.actions.partyArchived",
    "party.restored": "audit.actions.partyRestored",
    "asset.created": "audit.actions.assetCreated",
    "asset.updated": "audit.actions.assetUpdated",
    "asset.lifecycle_changed": "audit.actions.assetLifecycleChanged",
    "asset.identifier_added": "audit.actions.assetIdentifierAdded",
    "asset.identifier_changed": "audit.actions.assetIdentifierChanged",
    "asset.identifier_retired": "audit.actions.assetIdentifierRetired",
    "asset.archived": "audit.actions.assetArchived",
    "asset.restored": "audit.actions.assetRestored",
    "asset.relationship_started": "audit.actions.assetRelationshipStarted",
    "asset.relationship_ended": "audit.actions.assetRelationshipEnded",
    "asset.relationship_corrected": "audit.actions.assetRelationshipCorrected",
    "registry.import_completed": "audit.actions.registryImportCompleted",
    "service_request.created": "audit.actions.serviceRequestCreated",
    "service_request.updated": "audit.actions.serviceRequestUpdated",
    "service_request.cancelled": "audit.actions.serviceRequestCancelled",
    "service_request.closed": "audit.actions.serviceRequestClosed",
    "quote.created": "audit.actions.quoteCreated",
    "quote.revision.created": "audit.actions.quoteRevisionCreated",
    "quote.revision.edited": "audit.actions.quoteRevisionEdited",
    "quote.revision.issued": "audit.actions.quoteRevisionIssued",
    "quote.revision.superseded": "audit.actions.quoteRevisionSuperseded",
    "quote.revision.discarded": "audit.actions.quoteRevisionDiscarded",
    "quote.revision.withdrawn": "audit.actions.quoteRevisionWithdrawn",
    "quote.revision.expired": "audit.actions.quoteRevisionExpired",
    "quote.revision.rejected": "audit.actions.quoteRevisionRejected",
    "quote.accepted": "audit.actions.quoteAccepted",
    "quote.acceptance.withdrawn": "audit.actions.quoteAcceptanceWithdrawn",
    "quote.closed": "audit.actions.quoteClosed",
};
