packages:
    - "apps/*"
    - "packages/*"
allowBuilds:
    "@scarf/scarf": false
    esbuild: true
    unrs-resolver: true
minimumReleaseAgeExclude:
    - drizzle-kit@0.31.11
    - drizzle-orm@0.45.3
